
# Syntax highlighting
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:           :title
relative_permalinks: true

# Setup
timezone:            your timezone # eg. Asia/Kathmandu
locale:              your locale language # eg. en_us
name:				         jazz blues y soul
title:               jazz blues y soul
tagline:             'tagline'
description:         'Un género que revolucionó la musica y lo seguirá haciendo muchos años años más'
url:                 site url
rss:                 rss feed url
baseurl:             '/jazzbluesysoul/'
baseurl_posts_img:   '/Jazz Blues y Soul/assets/images/posts/'
baseurl_featured_img: '/mickey/assets/images/hero/'
baseurl_featured_thumbnail: '/mickey/assets/images/thumbnail/'
baseurl_javascripts: '/mickey/assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              disqus_shortname # get it on https://disqus.com/admin/

author:
  name:           	 Michelle Orozco
  url:            	 your site url
  facebook:          Michelle Orozc
  instagram:           michelleorozcodls
 # google_plus:       username
 # linkedin:          username
 # dribbble:          username
 # pinterest:         username
 # kiva:              username

# fb_admins:           your facebook profile id
# fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
